version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: 'postgresql://test_inventory:123456789@postgres:5432/inventory'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      JWT_SECRET: 'thisismysecrethahaha'
    volumes:
      - .:/app
    command: sh -c "npm run migrate && node dist/main.js"
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
